name: GLPI Agent Packaging

on:
  push:
    branches:
    - feature/github-action-windows-packaging
    - develop
    tags-ignore:
    - '**'

jobs:
  windows-packaging:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Restore points cache
      uses: pat-s/always-upload-cache@v2.0.0
      with:
        path: C:/Strawberry-perl-for-GLPI-Agent_build/restore
        key: windows-packaging-restore-points-${{ hashFiles('contrib\windows\packaging\PerlBuildJob.pm') }}
    - name: Update environment
      run: |
        echo '::add-path::C:\Strawberry\perl\bin'
        echo '::add-path::C:\Strawberry\perl\site\bin'
        echo '::add-path::C:\Strawberry\c\bin'
      shell: bash
    - name: Check environment
      run: |
        echo "PATH=%PATH%"
        perl --version
        perl -V
      shell: cmd
    - name: Install Perl::Dist::Strawberry
      run: |
        cpanm --notest --verbose Perl::Dist::Strawberry
      shell: cmd
    - name: Build package
      run: |
        perl contrib\windows\glpi-agent-packaging.pl --all
      shell: cmd
    - name: List generated files
      if: success() || failure()
      run: |
        dir C:\Strawberry-perl-for-GLPI-Agent_build\output
      shell: cmd
    - name: Upload Output artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v1
      with:
        name: Output
        path: C:\Strawberry-perl-for-GLPI-Agent_build\output
    - name: Upload MSI-Build artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v1
      with:
        name: MSI-Build
        path: C:\Strawberry-perl-for-GLPI-Agent_build\build\msi
