name: GLPI Agent Packaging

# Set publish_development_build to "yes" to publish development builds as pre-release
# Set number_of_development_build_to_keep to the number of development build to keep
# Set number_of_nightly_build_to_keep to the number of nightly release to keep
# Set number_of_nightly_build_to_keep to 0 to not publish nightly builds
env:
  publish_development_build: no
  number_of_development_build_to_keep: 3
  number_of_nightly_build_to_keep: 3
  macosx_notarize_support: yes

on:
  push:
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly publishing'
        required: true
        default: true
        type: boolean

jobs:
  setup-release:

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set-version.outputs.version }}
      upload_url: ${{ steps.create-tagged-release.outputs.upload_url }}
      create-release: ${{ steps.set-version.outputs.create-release }}
      tag_name: ${{ steps.set-version.outputs.tag_name }}
      build: ${{ steps.set-version.outputs.build }}
      releaseid: ${{ steps.create-tagged-release.outputs.id }}
      user-name: ${{ steps.set-version.outputs.user-name }}
      user-email: ${{ steps.set-version.outputs.user-email }}
      win32-signing: ${{ steps.set-version.outputs.win32-signing }}
      macosx-signing: ${{ steps.set-version.outputs.macosx-signing }}
      macosx-notarization: ${{ steps.set-version.outputs.macosx-notarization }}

    steps:
    - uses: actions/checkout@v6
    - name: Set version
      id: set-version
      run: |
        if [ "${{ vars.WIN32_SIGNING }}" == "no" ]; then
            echo "win32-signing=no" >>$GITHUB_OUTPUT
        elif [ -n "$CODESIGN_HOST" ]; then
            echo "win32-signing=yes" >>$GITHUB_OUTPUT
        else
            echo "win32-signing=no" >>$GITHUB_OUTPUT
        fi
        if [ -n "$APPSIGNID" -a -n "$INSTSIGNID" ]; then
            echo "macosx-signing=yes" >>$GITHUB_OUTPUT
            if [ "${{ env.macosx_notarize_support }}" == "yes" -a "${{ vars.MACOSX_NOTARIZE }}" != "no" ]; then
                NOTARIZE="yes"
            else
                NOTARIZE="no"
            fi
        else
            echo "macosx-signing=no" >>$GITHUB_OUTPUT
            NOTARIZE="no"
        fi
        if [ -z "${GITHUB_REF##*refs/tags/*}" ]; then
            # Abort publishing if MACOSX_SIGNING variable was set to "no"
            if [ "${{ vars.MACOSX_SIGNING }}" == "no" -a -n "$APPSIGNID" -a -n "$INSTSIGNID" ]; then
                echo "MACOSX_SIGNING has been disabled in GH variables. Fix it before publishing." >&2
                exit 1
            fi
            # Abort publishing if MACOSX_NOTARIZE variable was set to "no"
            if [ "${{ vars.MACOSX_NOTARIZE }}" == "no" -a "$NOTARIZE" == "yes" ]; then
                echo "MACOSX_NOTARIZE has been disabled in GH variables. Fix it before publishing." >&2
                exit 1
            fi
            VERSION="${GITHUB_REF#*refs/tags/}"
            echo "New release on $VERSION $tag"
            echo "create-release=yes" >>$GITHUB_OUTPUT
            echo "build=yes" >>$GITHUB_OUTPUT
            echo "tag_name=$VERSION" >>$GITHUB_OUTPUT
        else
            VERSION=$(perl -Ilib -MGLPI::Agent::Version -e 'print $GLPI::Agent::Version::VERSION')
            VERSION=${VERSION%-dev}-git${GITHUB_SHA:0:8}
            if [ "${{ github.event_name }}" = "schedule" -o "${{ inputs.nightly }}" = "true" -o "${{ env.publish_development_build }}" = "yes" ]; then
                if [ "${{ github.event_name }}" = "schedule" -o "${{ inputs.nightly }}" = "true" ]; then
                    TYPE=nightly
                    if [ -z "$PUBLISHING_TOKEN" ]; then
                        echo "No PUBLISHING_TOKEN defined to publish GLPI-Agent nightly builds"
                        echo "create-release=no" >>$GITHUB_OUTPUT
                        echo "build=no" >>$GITHUB_OUTPUT
                        exit 0
                    elif gh api /repos/{owner}/glpi-project.github.io/git/refs/tags/glpi-agent-development-$VERSION --silent 2>/dev/null; then
                        echo "GLPI-Agent v$VERSION still published as development build"
                        echo "create-release=no" >>$GITHUB_OUTPUT
                        echo "build=no" >>$GITHUB_OUTPUT
                        exit 0
                    fi
                else
                    TYPE=development
                fi
                SKIP_NIGHTLY="${{ env.number_of_nightly_build_to_keep }} $TYPE"
                # For nightly, we also check if we had any commit during the last 24 hours unless it is a manually forced run for which INPUT_NIGHTLY should be set
                if [ -z "$INPUT_NIGHTLY" -a "$SKIP_NIGHTLY" = "0 nightly" -o -z "$( git rev-list -n 1 --after="24 hours" ${{ github.sha }} )" ]; then
                    echo "No nightly release needed"
                    echo "create-release=no" >>$GITHUB_OUTPUT
                    echo "build=no" >>$GITHUB_OUTPUT
                else
                    echo "New $TYPE release as $VERSION version"
                    echo "create-release=${{ env.publish_development_build }}" >>$GITHUB_OUTPUT
                    echo "build=yes" >>$GITHUB_OUTPUT
                    echo "tag_name=$TYPE-$VERSION" >>$GITHUB_OUTPUT
                fi
            else
                echo "Just building $VERSION version"
                echo "create-release=no" >>$GITHUB_OUTPUT
                echo "build=yes" >>$GITHUB_OUTPUT
                echo "tag_name=development-$VERSION" >>$GITHUB_OUTPUT
                NOTARIZE="no"
            fi
        fi
        echo "version=$VERSION" >>$GITHUB_OUTPUT
        case "${VERSION#*-}" in
            $VERSION)
                echo "revname=v$VERSION" >>$GITHUB_OUTPUT
                echo "prerelease=false" >>$GITHUB_OUTPUT
                ;;
            test*)
                echo "revname=v${VERSION%-test*} Test release ${VERSION#*-test}" >>$GITHUB_OUTPUT
                echo "prerelease=true" >>$GITHUB_OUTPUT
                ;;
            beta*)
                echo "revname=v${VERSION%-beta*} Beta release ${VERSION#*-beta}" >>$GITHUB_OUTPUT
                echo "prerelease=true" >>$GITHUB_OUTPUT
                ;;
            *)
                echo "revname=v$VERSION Development release" >>$GITHUB_OUTPUT
                echo "prerelease=true" >>$GITHUB_OUTPUT
                ;;
        esac
        # Check if MacOSX packaging notarization is required
        echo "macosx-notarization=$NOTARIZE" >>$GITHUB_OUTPUT
        # Set user and mail for nightly release
        echo "user-name=$(git log --format='%an' HEAD^!)" >>$GITHUB_OUTPUT
        echo "user-email=$(git log --format='%ae' HEAD^!)" >>$GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISHING_TOKEN: ${{ secrets.PUBLISHING_TOKEN }}
        CODESIGN_HOST: ${{ secrets.CODESIGN_HOST }}
        APPSIGNID: ${{ vars.MACOSX_APPSIGNID }}
        INSTSIGNID: ${{ vars.MACOSX_INSTSIGNID }}
    - name: Generate release description
      id: github-release-body
      if: ${{ steps.set-version.outputs.create-release == 'yes' }}
      run: |
        tools/github-release-description.sh --version ${{ steps.set-version.outputs.version }} --tag ${{ steps.set-version.outputs.tag_name }}
      shell: bash
    - name: Create Tagged Release
      id: create-tagged-release
      uses: ncipollo/release-action@v1
      if: ${{ steps.set-version.outputs.create-release == 'yes' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag: ${{ steps.set-version.outputs.tag_name }}
        name: GLPI Agent ${{ steps.set-version.outputs.revname }}
        bodyFile: release-description.md
        draft: true
        prerelease: ${{ steps.set-version.outputs.prerelease }}

  macosx-packaging:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64

    if: ${{ needs.setup-release.outputs.build == 'yes' }}
    needs: setup-release

    steps:
    - uses: actions/checkout@v6
    - name: Image version
      id: runner-info
      run: echo "image-version=$ImageVersion" >>$GITHUB_OUTPUT
      shell: bash
    - name: Restore points cache
      uses: actions/cache@v5
      with:
        path: |
          contrib/macosx/*.gz
          contrib/macosx/*.sha1
          contrib/macosx/*.sha1.txt
          contrib/macosx/munkipkg
          contrib/macosx/build/perl*
          contrib/macosx/build/openssl*
          contrib/macosx/build/zlib*
          contrib/macosx/build/Applications
        key: ${{ matrix.os }}-${{ matrix.arch }}-packaging-restore-points-${{ runner.os }}-${{ runner.arch }}-${{ steps.runner-info.outputs.image-version }}-${{ hashFiles('contrib/macosx/glpi-agent-packaging.sh') }}
    - name: Import Application Signing Cert
      id: application-signing-cert
      uses: apple-actions/import-codesign-certs@v6
      if: ${{ needs.setup-release.outputs.macosx-signing == 'yes' && vars.MACOSX_SIGNING != 'no' }}
      with:
        p12-file-base64: ${{ secrets.MACOSX_APPLICATION_P12 }}
        p12-password: ${{ secrets.MACOSX_P12_PASSWORD }}
    - name: Import Installer Signing Cert
      id: installer-signing-cert
      uses: apple-actions/import-codesign-certs@v6
      if: ${{ needs.setup-release.outputs.macosx-signing == 'yes' && vars.MACOSX_SIGNING != 'no' }}
      with:
        p12-file-base64: ${{ secrets.MACOSX_INSTALLER_P12 }}
        p12-password: ${{ secrets.MACOSX_P12_PASSWORD }}
        create-keychain: false
        keychain-password: ${{ steps.application-signing-cert.outputs.keychain-password }}
    - name: Build package
      run: |
        # Handle repository variables to eventually disable code signing and notarization
        if [ -n "${{ vars.MACOSX_SIGNING }}" -o -n "${{ vars.MACOSX_NOTARIZE }}" ]; then
          echo "GH Variables:"
          if [ -n "${{ vars.MACOSX_SIGNING }}" ]; then
            echo " - MACOSX_SIGNING : ${{ vars.MACOSX_SIGNING }}"
            if [ "${{ vars.MACOSX_SIGNING }}" == "no" ]; then
              MACOSX_NOTARIZE="no"
              unset APPSIGNID INSTSIGNID
            fi
          fi
          if [ -n "${{ vars.MACOSX_NOTARIZE }}" ]; then
            echo " - MACOSX_NOTARIZE: ${{ vars.MACOSX_NOTARIZE }}"
            if [ "${{ vars.MACOSX_NOTARIZE }}" == "no" ]; then
              MACOSX_NOTARIZE="no"
              unset NOTARIZE_USER NOTARIZE_PASSWORD NOTARIZE_TEAMID
            fi
          fi
        fi
        ./contrib/macosx/glpi-agent-packaging.sh --arch ${{ matrix.arch }} --notarize $MACOSX_NOTARIZE
      env:
        APPSIGNID: ${{ vars.MACOSX_APPSIGNID }}
        INSTSIGNID: ${{ vars.MACOSX_INSTSIGNID }}
        NOTARIZE_USER: ${{ secrets.MACOSX_NOTARIZE_USER }}
        NOTARIZE_PASSWORD: ${{ secrets.MACOSX_NOTARIZE_PASSWORD }}
        NOTARIZE_TEAMID: ${{ vars.MACOSX_NOTARIZE_TEAMID }}
        MACOSX_NOTARIZE: ${{ needs.setup-release.outputs.macosx-notarization }}
        TAGNAME: ${{ needs.setup-release.outputs.tag_name }}
      shell: bash
    - name: List generated files
      if: success() || failure()
      run: |
        ls contrib/macosx/build
      shell: bash
    - name: Upload MacOSX built artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: MacOSX-Build-${{ matrix.arch }}
        path: |
          contrib/macosx/build/*.pkg
          contrib/macosx/build/*.dmg
    - name: Upload MacOSX Perl building debug artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v7
      with:
        name: MacOSX-Perl-Config-${{ matrix.arch }}
        path: |
          contrib/macosx/build/perl-*/config.h
          contrib/macosx/build/perl-*/config.sh
          contrib/macosx/build/perl-*/cflags
          contrib/macosx/build/perl-*/myconfig
          contrib/macosx/build/perl-*/Makefile
          contrib/macosx/build/perl-*/Policy.sh
          contrib/macosx/build/perl-*/hints/darwin.sh
    - name: Upload MacOSX PKG installer
      id: upload-macosx-pkg-asset
      if: ${{ needs.setup-release.outputs.create-release == 'yes' }}
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.setup-release.outputs.upload_url }}
        asset_path: contrib/macosx/build/GLPI-Agent-${{ needs.setup-release.outputs.version }}_${{ matrix.arch }}.pkg
        asset_name: GLPI-Agent-${{ needs.setup-release.outputs.version }}_${{ matrix.arch }}.pkg
        asset_content_type: application/octet-stream
    - name: Upload MacOSX DMG installer image
      id: upload-macosx-dmg-asset
      if: ${{ needs.setup-release.outputs.create-release == 'yes' }}
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.setup-release.outputs.upload_url }}
        asset_path: contrib/macosx/build/GLPI-Agent-${{ needs.setup-release.outputs.version }}_${{ matrix.arch }}.dmg
        asset_name: GLPI-Agent-${{ needs.setup-release.outputs.version }}_${{ matrix.arch }}.dmg
        asset_content_type: application/octet-stream
