name: GLPI Agent CI

# Perl lib caches are updated at least once a week
# but you can update last-cache-validation-date to invalidate perl lib caches
# last-cache-validation-date: 2022-09-21

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  macos-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: Update environment
      run: |
        PERL_PREFIX=$(perl -MConfig -e 'print $Config{prefix}')
        echo "$PERL_PREFIX/bin" >> $GITHUB_PATH
    - name: Check environment
      id: check-version
      run: |
        echo "PATH=$PATH"
        perl --version
        perl -V
        # Compute perl-version for current week to regen perl lib cache at least each week
        perl -e '@t = localtime; print "cache-version=".$^V."-".int(1+$t[7]/7)."\n"' >>$GITHUB_OUTPUT
    - name: Install libxml2 via brew
      run: brew install libxml2
    - name: Update environment to find latest libxml2
      run: |
        echo "$(brew --prefix)/opt/libxml2/bin" >> $GITHUB_PATH
    - name: Restore perl lib cache
      id: cache
      uses: actions/cache@v5
      with:
        path: |
            /opt/homebrew/Cellar/perl/*/lib/perl5/site_perl
            /opt/homebrew/Cellar/perl/*/bin
        key: macos-test-perl-${{ steps.check-version.outputs.cache-version }}-lib-cache-${{ hashFiles('Makefile.PL', '.github/workflows/glpi-agent-ci.yml') }}
    - name: Install Module::Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cpan -T Module::Install
    - name: Install cpanminus
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cpan -T App::cpanminus
    - name: Install deps
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cpanm --sudo --installdeps --verbose --notest .
        cpanm --sudo --verbose --notest Parse::EDID Crypt::DES Digest::HMAC
    - name: Prepare Makefile
      run: perl Makefile.PL
    - name: Run make
      run: make
    - name: Run tests
      run: make test
